### ISSUE TITLE
ValueError: too many value to unpack

### ISSUE THREAD

**Issue by mohitsahasrabudhe** [apoorva-dave/LicensePlateDetector#3] opened 2019-01-31 09:12 UTC
Hi, when I try to run the code on the default video12.mp4, it shows me two images and then throws and error.
![otsuiamge](https://user-images.githubusercontent.com/24694554/52043730-1098ed80-2506-11e9-9140-c28e6cd5c17f.png)
![videimage](https://user-images.githubusercontent.com/24694554/52043731-1098ed80-2506-11e9-9e4b-e71364855212.png)

```
$ python PredictCharacters.py
C:\Users\mohit\Anaconda3\lib\site-packages\skimage\filters\thresholding.py:271:                                                                                                                                   UserWarning: threshold_otsu is expected to work correctly only for grayscale ima                                                                                                                                  ges; image shape (1080, 1920, 3) looks like an RGB image
  warn(msg.format(image.shape))
Traceback (most recent call last):
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\backends\backend_q                                                                                                                                  t5.py", line 519, in _draw_idle
    self.draw()
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\backends\backend_a                                                                                                                                  gg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\artist.py", line 5                                                                                                                                  5, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1                                                                                                                                  475, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 14                                                                                                                                  1, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\artist.py", line 5                                                                                                                                  5, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", li                                                                                                                                  ne 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 14                                                                                                                                  1, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\artist.py", line 5                                                                                                                                  5, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 59                                                                                                                                  3, in draw
    renderer, renderer.get_image_magnification())
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 84                                                                                                                                  1, in make_image
    unsampled=unsampled)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 50                                                                                                                                  6, in _make_image
    self.get_filternorm() or 0.0, self.get_filterrad() or 0.0)
ValueError: 3-dimensional arrays must be of dtype unsigned byte, unsigned short,                                                                                                                                   float32 or float64
Traceback (most recent call last):
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\backends\backend_q                                                                                                                                  t5.py", line 519, in _draw_idle
    self.draw()
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\backends\backend_a                                                                                                                                  gg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\artist.py", line 5                                                                                                                                  5, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1                                                                                                                                  475, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 14                                                                                                                                  1, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\artist.py", line 5                                                                                                                                  5, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", li                                                                                                                                  ne 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 14                                                                                                                                  1, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\artist.py", line 5                                                                                                                                  5, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 59                                                                                                                                  3, in draw
    renderer, renderer.get_image_magnification())
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 84                                                                                                                                  1, in make_image
    unsampled=unsampled)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\matplotlib\image.py", line 50                                                                                                                                  6, in _make_image
    self.get_filternorm() or 0.0, self.get_filterrad() or 0.0)
ValueError: 3-dimensional arrays must be of dtype unsigned byte, unsigned short,                                                                                                                                   float32 or float64
(1080, 1920, 3)
Traceback (most recent call last):
  File "PredictCharacters.py", line 1, in <module>
    import SegmentCharacters
  File "D:\Applied Machine Learning\LicensePlateDetector\SegmentCharacters.py",                                                                                                                                   line 7, in <module>
    import DetectPlate
  File "D:\Applied Machine Learning\LicensePlateDetector\DetectPlate.py", line 7                                                                                                                                  6, in <module>
    min_row, min_col, max_row, max_col = region.bbox
ValueError: too many values to unpack (expected 4)

```

**Comment by apoorva-dave** [comment] 2019-01-31 09:17
Looks like a duplicate of #1

**Closed** 2019-02-12 09:09 UTC
